ALTER PROCEDURE Listado_Rollos
@Top INT, @Busqueda VARCHAR(20), @Impreso BIT, @Eliminado BIT
AS
BEGIN

SET NOCOUNT ON

	SELECT TOP (@Top) RD.ID,RD.NUM_ROLLO #CHAPA,RD.ROLLO #ROLLO, RD.COLADA,RD.PESO_KG,RD.SAE,RD.IMPRESO, RA.ID_RECEPCION, RA.PEDIDO,RD.FECHA_REG FECHA
	FROM RECEP_DETALLE RD JOIN RECEP_ALAMBRON RA
	ON RD.ID_RECEPCION=RA.ID
	WHERE 
	(
	--(RD.ELIMINADO = CASE WHEN @Eliminado = 1 THEN @Eliminado ELSE 0 END AND 
	(RD.COLADA LIKE '%'+@Busqueda+'%' OR RD.NUM_ROLLO LIKE '%'+@Busqueda+'%' OR ROLLO LIKE '%'+@Busqueda+'%' 
	OR RA.ID_RECEPCION LIKE '%'+@Busqueda+'%' OR RA.CONDUCE LIKE '%'+@Busqueda+'%')) 
	AND (RD.IMPRESO = CASE WHEN @Impreso = 1 THEN @Impreso ELSE 0 END AND 
	(RD.COLADA LIKE '%'+@Busqueda+'%' OR RD.NUM_ROLLO LIKE '%'+@Busqueda+'%' OR ROLLO LIKE '%'+@Busqueda+'%'
	OR RA.ID_RECEPCION LIKE '%'+@Busqueda+'%' OR RA.CONDUCE LIKE '%'+@Busqueda+'%'))

	OR ((RD.COLADA LIKE '%'+@Busqueda+'%' OR RD.NUM_ROLLO LIKE '%'+@Busqueda+'%' OR ROLLO LIKE '%'+@Busqueda+'%'
	OR RA.ID_RECEPCION LIKE '%'+@Busqueda+'%' OR RA.CONDUCE LIKE '%'+@Busqueda+'%') AND RD.IMPRESO=0)

	ORDER BY RD.FECHA_REG DESC
END


go
ALTER PROCEDURE Listado_recepcion
as
begin
set nocount on

	 SELECT R.ID,R.ID_RECEPCION,R.FECHA,R.ID_PEDIDO,R.PEDIDO, C.NOMBRE CHOFER, R.CONDUCE
	 FROM RECEP_ALAMBRON R JOIN CHOFER C ON C.ID_CHOFER=R.ID_CHOFER
	 ORDER BY R.FECHA DESC

end

GO
CREATE PROCEDURE Verificar_Recepcion_Alambron
@IdRecepcion VARCHAR(15)
AS
BEGIN
SET NOCOUNT ON
IF EXISTS (SELECT RA.ID,RA.ID_RECEPCION FROM RECEP_ALAMBRON RA WHERE RA.ID_RECEPCION=@IdRecepcion)
	BEGIN
		SELECT RA.ID,RA.ID_RECEPCION FROM RECEP_ALAMBRON RA WHERE RA.ID_RECEPCION=@IdRecepcion
	END
END

GO

CREATE PROCEDURE Obtener_Peso_Rollo_Alambron
@Rollo VARCHAR(15), @_Rollo VARCHAR(8) OUTPUT
AS
BEGIN
SET NOCOUNT ON

IF EXISTS (SELECT RD.PESO_QQS FROM RECEP_DETALLE RD WHERE ROLLO=@Rollo AND RD.SALIDA=0)
SET @_Rollo = (SELECT RD.PESO_QQS
FROM RECEP_DETALLE RD
WHERE ROLLO=@Rollo)
ELSE
SET @_Rollo='0'

END